"""Application identity is separate from character-card versions."""
APP_NAME = "静香助手"
APP_VERSION = "0.7.7"
APP_ID = "ShizukaAssistant"
DEFAULT_CHARACTER = "shizuka"
DEFAULT_PACK = "shizuka-side-motion"
